spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: user-service
file:
  upload-dir: ./uploads
  allowed-extensions: jpg,jpeg,png,gif,pdf,doc,docx,txt
  max-size: 10485760