eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

services:
  storage-service:
    url: ${STORAGE_SERVICE_URL:http://localhost:8088}

spring:
  cloud:
    config:
      override.system-property: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/pictorium}

logging:
  level:
    root: INFO

    org.springframework: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.validator: INFO
    org.springframework.security: DEBUG
    org.springdoc: INFO
    ru.tishembitov.pictorium: DEBUG

  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr(%-5level){highlight} %clr(%logger{36}){cyan} - %msg%n"

springdoc:
  api-docs:
    enabled: true
    path: /${spring.application.name}/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui

cors:
  allowed-origins: http://localhost:3000,http://localhost:5173
  allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

management:
  endpoints:
    web:
      exposure:
        include: "*"